name: Core Protected Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          # - l337-ssh
          # - init-github
          # - init-remote
          # - private-plugins
          - yaml
        os:
          # - macos-14
          - ubuntu-24.04
          # - windows-2022
        shell:
          - bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Install pkg dependencies
        run: bun install --frozen-lockfile --production

      # - name: Package into node binary
      #   uses: lando/pkg-action@v6
      #   id: pkg-action
      #   with:
      #     entrypoint: bin/lando
      #     filename: lando
      #     node-version: ${{ matrix.node-version }}
      #     options: --options dns-result-order=ipv4first
      #     upload: false
      #     pkg: '@yao-pkg/pkg@5.16.1'
      # - name: Install full deps
      #   run: npm clean-install --prefer-offline --frozen-lockfile
      # - name: Setup lando ${{ steps.pkg-action.outputs.file }}
      #   uses: lando/setup-lando@v3
      #   with:
      #     lando-version: ${{ steps.pkg-action.outputs.file }}
      #     telemetry: false
      #     config: |
      #       setup.skipCommonPlugins=true

      - name: Setup lando
        uses: lando/setup-lando@v3
        with:
          telemetry: false
          config: |
            setup.skipCommonPlugins=true
      - name: Temp run from source until bun build is ready
        run: |
          which lando || true
          where lando || true
          env
          bin/lando version

      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: './examples/${{ matrix.leia-test }}/README.md'
          cleanup-header: 'Destroy tests'
          shell: ${{ matrix.shell }}
          stdin: true
